name: base
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - shapely
  - requests
  - netcdf4
  - xarray
  - pytest
  - seaborn
  - statsmodels
  - pip
  - scikit-learn
  - ruff
  - geopandas
  - pip:
      - cftime
      - cartopy
      - nc-time-axis
      - netCDF4
      - geopy
      - matplotlib-scalebar
