name: base
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - shapely
  - requests
  - netcdf4
  - xarray
  - pytest
  - seaborn
  - statsmodels
  - pip
  - scikit-learn
  - ruff
  - pyproj
  - fiona
  - pyogrio
  - rtree
  - pip:
      - cftime
      - geopandas
      - geopy
      - matplotlib-scalebar
